name: moongo
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  firebase_auth: ^5.5.2
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  uuid: ^4.5.1
  shared_preferences: ^2.3.4
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^6.2.1
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.1
  stacked_generator: ^2.0.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
